#!/bin/bash

#
# Support mock config specification
#
MOCKOPTS=""
REPO="https://github.com/MythTV/mythweb.git"
while :; do
    case $1 in
        -r|--root)       # Takes an option argument; ensure it has been specified.
            if [ ! -z "$2" ]; then
                MOCKOPTS="$MOCKOPTS --root=$2"
                shift
            else
                printf 'ERROR: "--root" requires a non-empty option argument.\n'
                exit 1
            fi
            ;;
        --root=*)        # directly specified long argument
            MOCKOPTS="$MOCKOPTS $1"
            ;;
        --with)
            if [ ! -z "$2" ]; then
                MOCKOPTS="$MOCKOPTS --with=$2"
                shift
            else
                printf 'ERROR: "--with" requires a non-empty option argument.\n'
                exit 1
            fi
            ;;
        --with=*)
            MOCKOPTS="$MOCKOPTS $1"
            ;;
        --without)
            if [ ! -z "$2" ]; then
                MOCKOPTS="$MOCKOPTS --without=$2"
                shift
            else
                printf 'ERROR: "--without" requires a non-empty option argument.\n'
                exit 1
            fi
            ;;
        --without=*)
            MOCKOPTS="$MOCKOPTS $1"
            ;;
        --repo)
            if [ ! -z "$2" ]; then
                REPO="$2"
                shift
            else
                printf 'ERROR: "--repo" requires a non-empty option argument.\n'
                exit 1
            fi
            ;;
        --repo=*)
            REPO="${1#*=}"
            ;;
        --)              # End of all options.
            shift
            break
            ;;
        -?*)
            printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
            ;;
        *)               # Default case: No more options, so break out of the loop.
            break
     esac
     shift
done

GITCOMMITISH=$1

if [ "$GITCOMMITISH" == "" ]; then
    GITCOMMITISH="master"
fi

#
# First, we clone the repo, in order to obtain the
# description and commit hash for the specified
# version to build for/to (yes, this is sort of
# ugly, but while we can use ls-remote to get the
# commit hash, there is no (known) way to get the
# describe (maybe some future github api?))
#
TMPCLONEDIR=`mktemp -d`
pushd $TMPCLONEDIR >/dev/null
git clone $REPO mythweb
pushd mythweb >/dev/null
git checkout $GITCOMMITISH
if [ $? -ne 0 ]; then
    echo "Unable to checkout $GITCOMMITISH in $TMPCLONEDIR/mythweb"
    exit 1
fi

GITDESCRIBE=`git describe`
GITDESCRIBELONG=`git describe --long`
GITCOMMIT=`git rev-parse HEAD`
GITCOMMITSHORT=`git rev-parse --short HEAD`
GITCOMMITDATE=`TZ=UTC git --no-pager log -1 --format='%cs' | cut --characters=1-4,6-7,9-10 | grep -E '^[[:digit:]]{8}$'`

popd >/dev/null
popd >/dev/null

# MythTV project specific tag format
if ! [ ${GITDESCRIBE:0:1} == 'v' ]; then
    echo "Unable to parse mythweb git describe $GITDESCRIBE from $TMPCLONEDIR/mythweb"
    exit 1
fi

# Adjust git-describe to acceptable RPM format
RPMVERSION=${GITDESCRIBE:1}
RPMVERSION=${RPMVERSION//-/.}

# Determine if we are at a post branch/tag checkout
# and adjust the describe to use the current
# recommendations for the package name
if [ "$GITDESCRIBE" == "$GITDESCRIBELONG" ] ; then
    RPMVERSION=${RPMVERSION:0:-(${#GITCOMMITSHORT} + 1)}${GITCOMMITDATE}git${GITCOMMITSHORT}
fi

#
# Announce to world and dog what we are doing
#
echo "----"
echo "Building mythweb version $RPMVERSION at commit $GITCOMMIT"
echo "----"

#
# Build an expanded SPEC file with our definitions so that
# the src.rpm will be reproducably buildable outside of this
# build script
#
TMPSDIR=`mktemp -d`
cp -r SOURCES $TMPSDIR/
cp -r SPECS $TMPSDIR/
sed -i -e "s/^Version: .*/Version:        $RPMVERSION/" $TMPSDIR/SPECS/mythweb.spec
sed -i -e "s/^%global commit .*/%global commit $GITCOMMIT/" $TMPSDIR/SPECS/mythweb.spec

# Use git-archive to create source tarball from our clone
pushd $TMPCLONEDIR/mythweb > /dev/null
git archive --output $TMPSDIR/SOURCES/mythweb-$GITCOMMIT.tar.gz --prefix mythweb-$GITCOMMIT/ $GITCOMMIT
popd >/dev/null

# Cleanup our clone
rm -rf $TMPCLONEDIR/mythweb
rmdir $TMPCLONEDIR


#
# Build buildable src.rpm
#
TMPSRCDIR=`mktemp -d`
# Build src.rpm
mock $MOCKOPTS --define="dist %{nil}" --resultdir=$TMPSRCDIR --spec=$TMPSDIR/SPECS/mythweb.spec --sources=$TMPSDIR/SOURCES --buildsrpm
if [ $? -ne 0 ]; then
    echo "Unable to build source rpm"
    exit 1
fi
SRCRPM=`ls $TMPSRCDIR/*$RPMVERSION*.src.rpm`
if [ ! -f "$SRCRPM" ]; then
    echo "Source RPM was not built"
    exit 1
fi

TMPTGTDIR=`mktemp -d`
mock $MOCKOPTS --resultdir=$TMPTGTDIR --rebuild $SRCRPM
if [ $? -ne 0 ]; then
    echo "Unable to build rpm"
    exit 1
fi

BUILTRPMS=`find $TMPTGTDIR -name \*.rpm -print`

mkdir -p SRPMS RPMS
for fn in ${BUILTRPMS}
do
    [[ "$fn" =~ ^.*\.(.+)\.rpm$ ]] &&
        (
            archdir="${BASH_REMATCH[1]}"
            if [ "$archdir" == "src" ]; then
                cp $fn SRPMS/
            else
                if [ "$archdir" == "i686" ]; then
                    archdir="i386"
                elif [ "$archdir" == "armv7hl" ]; then
                    archdir="armhfp"
                fi
                mkdir -p RPMS/$archdir
                cp $fn RPMS/$archdir/
            fi
        )
done


# Cleanup
rm -f $TMPSRCDIR/*.log
rm -f $TMPSRCDIR/*.rpm
rmdir $TMPSRCDIR
rm -rf $TMPTGTDIR/*.log
rm -rf $TMPTGTDIR/*.rpm
rmdir $TMPTGTDIR
rm -rf $TMPSDIR/SPECS
rm -rf $TMPSDIR/SOURCES
rmdir $TMPSDIR
