#!/bin/bash

VERSION=$1

if [ "$VERSION" == "" ]; then
    echo "HDHRDVR VERSION must be provided as argument."
    exit 1
fi

# Use spectool to get sources if needed and available
if [ ! -f "SOURCES/hdhomerun_record_linux_$VERSION" -a -x /usr/bin/spectool ]; then
  /usr/bin/spectool -d "HDHRDVR_VERSION $VERSION" -g -s 0 -C SOURCES SPECS/hdhomerun-record.spec
fi

if [ ! -f "SOURCES/hdhomerun_record_linux_$VERSION" ]; then
    echo "SOURCES/hdhomerun_record_linux_$VERSION binary not found."
    exit 1
fi

PKGMGR=''
if [ ! -x "/usr/bin/dnf" ]; then
    PKGMGR='--yum'
fi

TMPDIR=`mktemp -d`

ARCH=`arch`

CFGARCH=$ARCH
if [ "$CFGARCH" == "armv7l" ]; then
    CFGARCH='armhfp'
fi

EL=(`ls build_cfgs/ | grep "centos-[[:digit:]]\\+-$CFGARCH.cfg" | sed -n "s/centos-\([0-9]\+\)-$CFGARCH.cfg/\1/p" | sort -n`)
ELBASE=${EL[0]}
FC=(`ls /etc/mock/ | grep "fedora-[[:digit:]]\\+-$CFGARCH.cfg" | sed -n "s/fedora-\([0-9]\+\)-$CFGARCH.cfg/\1/p" | sort -n | tail -3`)
FCBASE=${FC[0]}

# Create resultdir directories
for el in ${EL[@]}
do
    mkdir -p RPMS/el/$el/i386 RPMS/el/$el/x86_64
    if [ $el -ne 6 ]; then
        mkdir -p RPMS/el/$el/armhfp RPMS/el/$el/aarch64
    fi
done
for fc in ${FC[@]}
do
    mkdir -p RPMS/fedora/$fc/i386 RPMS/fedora/$fc/x86_64 RPMS/fedora/$fc/armhfp RPMS/fedora/$fc/aarch64
done

# Build src.rpm
/usr/bin/mock -r build_cfgs/centos-$ELBASE-$CFGARCH.cfg --define "HDHRDVR_VERSION $VERSION" --define "dist %{nil}" --buildsrpm --spec=SPECS/hdhomerun-record.spec --sources=SOURCES --resultdir=$TMPDIR --disable-plugin=ccache $PKGMGR
SRCRPM=`ls $TMPDIR/*$VERSION*.src.rpm`
if [ ! -f "$SRCRPM" ]; then
    echo "Source RPM was not built"
    exit 1
fi

# Build arch specific rpms
for fc in ${FC[@]}
do
    /usr/bin/mock -r fedora-$fc-$CFGARCH --define "HDHRDVR_VERSION $VERSION" --define "dist .fc$fc" --resultdir=RPMS/fedora/$fc/$CFGARCH --disable-plugin=ccache $PKGMGR $SRCRPM
    if [ "$ARCH" == "x86_64" ]; then
        /usr/bin/mock -r fedora-$fc-$CFGARCH --define "HDHRDVR_VERSION $VERSION" --define "dist .fc$fc" --target=i686 --resultdir=RPMS/fedora/$fc/i386 --disable-plugin=ccache $PKGMGR $SRCRPM
    fi
done
for el in ${EL[@]}
do
    /usr/bin/mock -r build_cfgs/centos-$el-$CFGARCH.cfg --define "HDHRDVR_VERSION $VERSION" --define "dist .el$el" --resultdir=RPMS/el/$el/$CFGARCH --disable-plugin=ccache $PKGMGR $SRCRPM
    if [ "$ARCH" == "x86_64" ]; then
        /usr/bin/mock -r build_cfgs/centos-$el-$CFGARCH.cfg --define "HDHRDVR_VERSION $VERSION" --define "dist .el$el" --target=i686 --resultdir=RPMS/el/$el/i386 --disable-plugin=ccache $PKGMGR $SRCRPM
    fi
done

# Clean up after ourselves
for f in "$TMPDIR/root.log" "$TMPDIR/state.log" "$TMPDIR/build.log" "$TMPDIR/hw_info.log" "$SRCRPM"
do
    if [ -f "$f" ]; then
        rm "$f"
    fi
done
rmdir $TMPDIR
